import React from 'react'
import _Form from '@/components/form/form'
import Head from "next/head";
import styles from  '@/styles/Home.module.css'


export default function Contact() {




  return (
<div style={{"padding":"10px" ,"display":"grid"}}>

<Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
    
      </Head>

<h4 className={styles.tetst}>Contacwwt Us</h4>

<_Form/>
 </div>
   
)
  }


  